version: '3.8'

services:
  app:
    build: .
    container_name: contact_list_app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://sakharehiteshh:Flash%401998@contactlistdb.gcvpwjj.mongodb.net/contactlist?retryWrites=true&w=majority
    volumes:
      - .:/usr/src/app
